app = 'unrotapp'
primary_region = 'gru'

[build]

[env]
  SPRING_PROFILES_ACTIVE = 'prod'
  JAVA_OPTS = '-Xmx300m -Xms300m -XX:+UseSerialGC -XX:MaxMetaspaceSize=96m'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '120s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
