spring:
  application:
    name: unrotapp

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo

app:
  security:
    jwt:
      secret: ${JWT_SECRET:ZGV2LWNoYW5nZS1tZS1wbGVhc2UtMzItY2hhcnMtbWlu}
      issuer: unrotapp
      ttl: 1h
  storage:
    seaweedfs:
      master-url: ${SEAWEEDFS_MASTER_URL:http://localhost:9333}

spring.servlet.multipart:
  max-file-size: 500MB
  max-request-size: 500MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 30s
