spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:postgres-service}:${DB_PORT:5432}/${DB_NAME:demo}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: validate
